name: mark_file

on:
  push: 
    branches:
        test/mark_file

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Execute Check Process
        run: |
            chmod +x .scripts/mark_file.sh 
            .scripts/mark_file.sh
        shell: bash

      - uses: stefanzweifel/git-auto-commit-action@v5